version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    networks:
      - backend
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
      - 'REDIS_HOST=redis'
      - 'REDIS_PASSWORD=null'
      - 'REDIS_PORT=6379'
  
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    networks:
      - frontend
      - backend
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
  
  redis:
    image: redis:alpine

  # The Database
  database:
    image: mysql:5.6
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=homestead'
      - 'MYSQL_USER=homestead'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
    ports:
      - '33061:3306'

volumes:
  dbdata:
networks:
  frontend:
  backend:
